# 名前
name: "Build html and Deploy to GitHub Pages"

# onセクション：jobsの実行トリガーを記載
on:
  push:
# ----------------------------
# よく使われるのは以下
# push : リモートリポジトリのpush時
# pull_request : プルリクエスト作成時
# deployment : デプロイ時
# release : リリース時
# issues : GitHub Issues関連の処理発生時
# schedule : cronによる定期実行
# ----------------------------

# jobsセクション：実際のジョブを記載
jobs:
# jobセクション配下に1つ以上のjobIDを定義し、各jobIDは並列に処理される
  deploy_html: #jobID
    name: deploy_html
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: SetupPython
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: x64
    
    - name: Install sphinx
      run: |
        pip install -U sphinx
