name: Build html and Deploy to GitHub Pages

# jobsセクション：実際のジョブを記載
jobs:
  # "my_first_job"というジョブIDでジョブを定義
  my_first_job:
    name: My first job
  # "my_second_job"というジョブIDでジョブを定義
  my_second_job:
    name: My second job
